In [1]:
import torch

In [12]:
x = torch.empty(2,3)

In [14]:
r = torch.rand(3,2)

In [20]:
z = torch.zeros(2,2,dtype=torch.float16)

In [21]:
z

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float16)

In [22]:
print(x.dtype)

torch.float32


In [25]:
x = torch.tensor([2.5,1])

In [27]:
x.dtype

torch.float32

In [32]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [33]:
y

tensor([[0.2343, 0.4107],
        [0.4363, 0.4684]])

In [34]:
#add x into y, equivalent y = x+y or y = torch.add(x,y)
y.add_(x)

tensor([[1.1582, 1.2903],
        [1.1737, 1.2735]])

In [41]:
x = torch.rand(5,3)
x

tensor([[0.6773, 0.9423, 0.1748],
        [0.7091, 0.4766, 0.4161],
        [0.4326, 0.1532, 0.2478],
        [0.0207, 0.6470, 0.7281],
        [0.8331, 0.9314, 0.0094]])

In [42]:
print(x[:,0])

tensor([0.6773, 0.7091, 0.4326, 0.0207, 0.8331])


In [52]:
y = x.view(15)
y


tensor([0.6773, 0.9423, 0.1748, 0.7091, 0.4766, 0.4161, 0.4326, 0.1532, 0.2478,
        0.0207, 0.6470, 0.7281, 0.8331, 0.9314, 0.0094])

In [54]:
#reshape, -1 indicate any number fit in, in this example is 3
y = x.view(-1,5)
y

tensor([[0.6773, 0.9423, 0.1748, 0.7091, 0.4766],
        [0.4161, 0.4326, 0.1532, 0.2478, 0.0207],
        [0.6470, 0.7281, 0.8331, 0.9314, 0.0094]])

In [55]:
import numpy as np

In [56]:
#create a numpy from tensor
a = torch.ones(5)
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [57]:
print(type(b))

<class 'numpy.ndarray'>


In [58]:
#when in cpu they share same memory location
a.add_(1)
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [59]:
#create a tensor from numpy
a = np.ones(5)
b = torch.from_numpy(a)
a+=1
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [64]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    #create tensor and put it on gpu
    x = torch.ones(5, device = device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y
    z = z.to("cpu")
print(z)

tensor([2., 2., 2., 2., 2.])


In [67]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    a = torch.ones(5, device = device)
    b = a.cpu().detach().numpy()
    a+=1
    print(b)

[1. 1. 1. 1. 1.]
