In [1]:
import torch

In [60]:
#python will remember the computation graph and provide backpropagation to get gradient
x = torch.randn(3, requires_grad=True)

In [68]:
x

tensor([ 0.8515, -0.1005,  1.3627], requires_grad=True)

In [69]:
y=x+x

In [70]:
print(y)

tensor([ 1.7031, -0.2010,  2.7254], grad_fn=<AddBackward0>)


In [71]:
z = y*y*2

In [72]:
print(z)

tensor([ 5.8010,  0.0808, 14.8552], grad_fn=<MulBackward0>)


In [73]:
z = z.mean()
print(z)

tensor(6.9123, grad_fn=<MeanBackward0>)


In [74]:
z.backward() #dz/dx, z must not be a matrix
print(x.grad)

tensor([5.8749, 0.7975, 8.6010])


In [76]:
#how to avoid tracking sometimes
x.requires_grad_(False)
y = x.detach()
with torch.no_grad():
    y = x+2
    print(y)


tensor([2.8515, 1.8995, 3.3627])


In [80]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(2):
    model_output = (weights*3).sum()
    print(model_output)
    model_output.backward()
    print(weights.grad)
    #without following line, since you are introduce backward that not actually in result, grad is wrong
    #weights.grad.zero_()

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([6., 6., 6., 6.])
